[2022-08-19 18:19:33,606] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-19T18:19:26.975904+00:00 [queued]>
[2022-08-19 18:19:33,616] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-19T18:19:26.975904+00:00 [queued]>
[2022-08-19 18:19:33,616] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:19:33,616] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-19 18:19:33,616] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:19:33,678] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-19 18:19:26.975904+00:00
[2022-08-19 18:19:33,686] {standard_task_runner.py:52} INFO - Started process 824 to run task
[2022-08-19 18:19:33,690] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'manual__2022-08-19T18:19:26.975904+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmppk_s5t7j', '--error-file', '/tmp/tmp0sw2fwxm']
[2022-08-19 18:19:33,691] {standard_task_runner.py:80} INFO - Job 126: Subtask load_data
[2022-08-19 18:19:33,788] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data manual__2022-08-19T18:19:26.975904+00:00 [running]> on host 3a5c2d0be6af
[2022-08-19 18:19:34,144] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T18:19:26.975904+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T18:19:26.975904+00:00
[2022-08-19 18:19:40,357] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 18:19:40,374] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Satellite_Data, task_id=load_data, execution_date=20220819T181926, start_date=20220819T181933, end_date=20220819T181940
[2022-08-19 18:19:40,421] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 18:19:40,469] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
