[2022-08-18 16:32:34,092] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data scheduled__2022-08-17T16:32:25.188706+00:00 [queued]>
[2022-08-18 16:32:34,107] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data scheduled__2022-08-17T16:32:25.188706+00:00 [queued]>
[2022-08-18 16:32:34,107] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 16:32:34,107] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-18 16:32:34,107] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 16:32:34,149] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-17 16:32:25.188706+00:00
[2022-08-18 16:32:34,159] {standard_task_runner.py:52} INFO - Started process 1238 to run task
[2022-08-18 16:32:34,165] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'scheduled__2022-08-17T16:32:25.188706+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpdklpr6j2', '--error-file', '/tmp/tmpqf76qpb_']
[2022-08-18 16:32:34,165] {standard_task_runner.py:80} INFO - Job 66: Subtask load_data
[2022-08-18 16:32:34,288] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data scheduled__2022-08-17T16:32:25.188706+00:00 [running]> on host b4db7d4790c9
[2022-08-18 16:32:34,404] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T16:32:25.188706+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-17T16:32:25.188706+00:00
[2022-08-18 16:32:34,760] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbConnector.py", line 7, in load_into_database
    data = pd.read_json('/opt/airflow/dags/tempSatelliteData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Unmatched ''"' when when decoding 'string'
[2022-08-18 16:32:34,775] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Satellite_Data, task_id=load_data, execution_date=20220817T163225, start_date=20220818T163234, end_date=20220818T163234
[2022-08-18 16:32:34,823] {standard_task_runner.py:97} ERROR - Failed to execute job 66 for task load_data (Unmatched ''"' when when decoding 'string'; 1238)
[2022-08-18 16:32:34,859] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 16:32:35,175] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
