[2022-08-19 18:04:33,976] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data scheduled__2022-08-18T16:32:25.188706+00:00 [queued]>
[2022-08-19 18:04:33,986] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data scheduled__2022-08-18T16:32:25.188706+00:00 [queued]>
[2022-08-19 18:04:33,986] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:33,986] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-19 18:04:33,986] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 18:04:34,013] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): using_pyspark_to_analyze_streaming_data> on 2022-08-18 16:32:25.188706+00:00
[2022-08-19 18:04:34,019] {standard_task_runner.py:52} INFO - Started process 128 to run task
[2022-08-19 18:04:34,024] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'using_pyspark_to_analyze_streaming_data', 'scheduled__2022-08-18T16:32:25.188706+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpzhuncepy', '--error-file', '/tmp/tmp6e6cszgx']
[2022-08-19 18:04:34,025] {standard_task_runner.py:80} INFO - Job 122: Subtask using_pyspark_to_analyze_streaming_data
[2022-08-19 18:04:34,110] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data scheduled__2022-08-18T16:32:25.188706+00:00 [running]> on host 3a5c2d0be6af
[2022-08-19 18:04:34,222] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=using_pyspark_to_analyze_streaming_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T16:32:25.188706+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T16:32:25.188706+00:00
[2022-08-19 18:04:34,223] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-19 18:04:34,223] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/L/Programming/dataEng/spaceApp/Streaming/read_data.py']
[2022-08-19 18:04:34,238] {subprocess.py:85} INFO - Output:
[2022-08-19 18:04:34,350] {subprocess.py:92} INFO - python3: can't open file '/home/L/Programming/dataEng/spaceApp/Streaming/read_data.py': [Errno 2] No such file or directory
[2022-08-19 18:04:34,353] {subprocess.py:96} INFO - Command exited with return code 2
[2022-08-19 18:04:34,378] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-19 18:04:34,381] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Satellite_Data, task_id=using_pyspark_to_analyze_streaming_data, execution_date=20220818T163225, start_date=20220819T180433, end_date=20220819T180434
[2022-08-19 18:04:34,414] {standard_task_runner.py:97} ERROR - Failed to execute job 122 for task using_pyspark_to_analyze_streaming_data (Bash command failed. The command returned a non-zero exit code 2.; 128)
[2022-08-19 18:04:34,433] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-19 18:04:34,513] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
