[2022-08-28 18:18:13,025] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-28T18:12:59.429354+00:00 [queued]>
[2022-08-28 18:18:13,041] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_data manual__2022-08-28T18:12:59.429354+00:00 [queued]>
[2022-08-28 18:18:13,041] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 18:18:13,041] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-28 18:18:13,041] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 18:18:13,081] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2022-08-28 18:12:59.429354+00:00
[2022-08-28 18:18:13,088] {standard_task_runner.py:52} INFO - Started process 3063 to run task
[2022-08-28 18:18:13,094] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_data', 'manual__2022-08-28T18:12:59.429354+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpbd71_00v', '--error-file', '/tmp/tmp3rf18lld']
[2022-08-28 18:18:13,094] {standard_task_runner.py:80} INFO - Job 194: Subtask load_data
[2022-08-28 18:18:13,317] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_data manual__2022-08-28T18:12:59.429354+00:00 [running]> on host b42bb8df931d
[2022-08-28 18:18:13,546] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T18:12:59.429354+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T18:12:59.429354+00:00
[2022-08-28 18:18:22,836] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 18:18:22,869] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Satellite_Data, task_id=load_data, execution_date=20220828T181259, start_date=20220828T181813, end_date=20220828T181822
[2022-08-28 18:18:23,028] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 18:18:23,090] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
