[2022-08-19 02:45:02,144] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:44:40.366905+00:00 [queued]>
[2022-08-19 02:45:02,156] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:44:40.366905+00:00 [queued]>
[2022-08-19 02:45:02,156] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 02:45:02,157] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-19 02:45:02,157] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 02:45:02,202] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): using_pyspark_to_analyze_streaming_data> on 2022-08-19 02:44:40.366905+00:00
[2022-08-19 02:45:02,212] {standard_task_runner.py:52} INFO - Started process 1737 to run task
[2022-08-19 02:45:02,216] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'using_pyspark_to_analyze_streaming_data', 'manual__2022-08-19T02:44:40.366905+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpnpsy91f7', '--error-file', '/tmp/tmpdijou3a1']
[2022-08-19 02:45:02,216] {standard_task_runner.py:80} INFO - Job 113: Subtask using_pyspark_to_analyze_streaming_data
[2022-08-19 02:45:02,328] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.using_pyspark_to_analyze_streaming_data manual__2022-08-19T02:44:40.366905+00:00 [running]> on host a5d93a99773b
[2022-08-19 02:45:02,481] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=using_pyspark_to_analyze_streaming_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T02:44:40.366905+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T02:44:40.366905+00:00
[2022-08-19 02:45:02,482] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-19 02:45:02,482] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/L/Programming/dataEng/spaceApp/Streaming/read_data.py']
[2022-08-19 02:45:02,500] {subprocess.py:85} INFO - Output:
[2022-08-19 02:45:02,606] {subprocess.py:92} INFO - python3: can't open file '/home/L/Programming/dataEng/spaceApp/Streaming/read_data.py': [Errno 2] No such file or directory
[2022-08-19 02:45:02,608] {subprocess.py:96} INFO - Command exited with return code 2
[2022-08-19 02:45:02,648] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-19 02:45:02,654] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Satellite_Data, task_id=using_pyspark_to_analyze_streaming_data, execution_date=20220819T024440, start_date=20220819T024502, end_date=20220819T024502
[2022-08-19 02:45:02,696] {standard_task_runner.py:97} ERROR - Failed to execute job 113 for task using_pyspark_to_analyze_streaming_data (Bash command failed. The command returned a non-zero exit code 2.; 1737)
[2022-08-19 02:45:02,747] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-19 02:45:02,828] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
